version: "3.5"
services:
  frontend:
     build: ./Frontend-Angular/appsdc
      networks:
      - app-network
     ports:
      - "4200:80"
  backend:
     build: ./Backend-NodeJs
      networks:
      - app-network
     ports:
      - "3000:3000"