version: "3.6"
services:
  server:
    build: ./Backend-NodeJs
    ports:
      - "3000:3000"
    container_name: backend

  nginx:
    build: 
      context: .
      dockerfile: ./Webserver/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
    container_name: frontend

  gate:
    build: 
      context: .
      dockerfile: ./Webserver/Dockerfile
    ports:
      - "80:8082"
    depends_on:
      - frontend
    restart: always
    container_name: nginx
