version: "3.5"
services:
  frontend:
     build: ./Frontend-Angular/appsdc
     ports:
      - "80:80"
      - "443:443"
     volumes:
      - ./Webserver/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./Webserver/certbot/www:/var/www/certbot/:ro
      - ./Webserver/certbot/conf/:/etc/nginx/ssl/:ro

  backend:
     build: ./Backend-NodeJs
     ports:
      - "3000:3000"
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./Webserver/certbot/www/:/var/www/certbot/:rw
      - ./Webserver/certbot/conf/:/etc/letsencrypt/:rw
     