version: "3.6"
services:
  angular:
    build: 
      context: .
      dockerfile: ./Frontend-Angular/Dockerfile
    restart: always
    ports:
      - "80:80"
    container_name: angular

  nginx:
    build: 
      context: .
      dockerfile: ./LoadBalancer/Dockerfile
    ports:
      - "80:80"
    restart: always
    container_name: mean
    links:
      - angular

